import { BrandProfile } from "@/hooks/useBrandProfiles";

const scoreLabels = {
  semantic_clarity_score: "Semantic Clarity",
  intent_alignment_score: "Intent Alignment",
  authority_score: "Authority Signals",
  consistency_score: "Consistency",
  explainability_score: "Explainability",
  recall_score: "Overall Recall Score",
};

export function exportToCSV(brands: BrandProfile[], filename: string = "brand-comparison") {
  const headers = [
    "Brand Name",
    "Category",
    "Overall Recall Score",
    "Semantic Clarity",
    "Intent Alignment",
    "Authority Signals",
    "Consistency",
    "Explainability",
    "Is Optimized",
    "Last Updated",
  ];

  const rows = brands.map((brand) => [
    brand.brand_name,
    brand.category || "N/A",
    brand.recall_score,
    brand.semantic_clarity_score,
    brand.intent_alignment_score,
    brand.authority_score,
    brand.consistency_score,
    brand.explainability_score,
    brand.is_optimized ? "Yes" : "No",
    new Date(brand.updated_at).toLocaleDateString(),
  ]);

  const csvContent = [
    headers.join(","),
    ...rows.map((row) => row.map((cell) => `"${cell}"`).join(",")),
  ].join("\n");

  downloadFile(csvContent, `${filename}.csv`, "text/csv");
}

export function exportToPDF(brands: BrandProfile[], filename: string = "brand-comparison") {
  // Generate HTML content for PDF
  const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <title>Brand Comparison Report</title>
  <style>
    body { font-family: Arial, sans-serif; padding: 40px; color: #333; }
    h1 { color: #7c3aed; border-bottom: 2px solid #7c3aed; padding-bottom: 10px; }
    h2 { color: #555; margin-top: 30px; }
    table { width: 100%; border-collapse: collapse; margin-top: 20px; }
    th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
    th { background: #7c3aed; color: white; }
    tr:nth-child(even) { background: #f9f9f9; }
    .score { font-weight: bold; }
    .high { color: #22c55e; }
    .medium { color: #f59e0b; }
    .low { color: #ef4444; }
    .footer { margin-top: 40px; font-size: 12px; color: #888; text-align: center; }
    .brand-section { page-break-inside: avoid; margin-bottom: 30px; }
    .score-bar { height: 20px; background: #e5e7eb; border-radius: 4px; overflow: hidden; }
    .score-fill { height: 100%; background: linear-gradient(90deg, #7c3aed, #a855f7); }
  </style>
</head>
<body>
  <h1>🧠 Recall - Brand Comparison Report</h1>
  <p>Generated on ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}</p>
  
  <h2>Score Comparison Table</h2>
  <table>
    <thead>
      <tr>
        <th>Component</th>
        ${brands.map((b) => `<th>${b.brand_name}</th>`).join("")}
      </tr>
    </thead>
    <tbody>
      ${Object.entries(scoreLabels)
        .map(
          ([key, label]) => `
        <tr>
          <td><strong>${label}</strong></td>
          ${brands
            .map((b) => {
              const score = b[key as keyof BrandProfile] as number || 0;
              const colorClass = score >= 70 ? "high" : score >= 40 ? "medium" : "low";
              return `<td class="score ${colorClass}">${score}</td>`;
            })
            .join("")}
        </tr>
      `
        )
        .join("")}
    </tbody>
  </table>

  <h2>Brand Details</h2>
  ${brands
    .map(
      (brand) => `
    <div class="brand-section">
      <h3>${brand.brand_name} ${brand.is_optimized ? "✓ Optimized" : ""}</h3>
      <p><strong>Category:</strong> ${brand.category || "N/A"}</p>
      <p><strong>Description:</strong> ${brand.description || "No description"}</p>
      <p><strong>Target Audience:</strong> ${brand.target_audience || "N/A"}</p>
      <p><strong>Value Proposition:</strong> ${brand.value_proposition || "N/A"}</p>
    </div>
  `
    )
    .join("")}

  <div class="footer">
    <p>Report generated by Recall AI - AI-Readiness Optimization Platform</p>
    <p>Scores are simulation estimates and do not guarantee external AI rankings.</p>
  </div>
</body>
</html>
  `;

  // Open in new window for printing
  const printWindow = window.open("", "_blank");
  if (printWindow) {
    printWindow.document.write(htmlContent);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
    }, 250);
  }
}

function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}